// Mocks generated by Mockito 5.4.5 from annotations
// in mamlakat_alabtal/test/features/habits/presentation/cubit/habits_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mamlakat_alabtal/features/habits/domain/entities/habit_entry.dart'
    as _i6;
import 'package:mamlakat_alabtal/features/habits/domain/entities/habit_summary.dart'
    as _i3;
import 'package:mamlakat_alabtal/features/habits/domain/repositories/habits_repository.dart'
    as _i2;
import 'package:mamlakat_alabtal/features/habits/domain/usecases/get_today_summary_usecase.dart'
    as _i8;
import 'package:mamlakat_alabtal/features/habits/domain/usecases/submit_entry_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHabitsRepository_0 extends _i1.SmartFake
    implements _i2.HabitsRepository {
  _FakeHabitsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHabitSummary_1 extends _i1.SmartFake implements _i3.HabitSummary {
  _FakeHabitSummary_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubmitEntryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitEntryUseCase extends _i1.Mock
    implements _i4.SubmitEntryUseCase {
  MockSubmitEntryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HabitsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHabitsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HabitsRepository);

  @override
  _i5.Future<String> call(_i6.HabitEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [entry],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #call,
            [entry],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [GetTodaySummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodaySummaryUseCase extends _i1.Mock
    implements _i8.GetTodaySummaryUseCase {
  MockGetTodaySummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HabitsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHabitsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HabitsRepository);

  @override
  _i5.Future<_i3.HabitSummary> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.HabitSummary>.value(_FakeHabitSummary_1(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.HabitSummary>);
}
