import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:intl/intl_standalone.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('ar'),
    Locale('en'),
  ];

  // Helper method to get localized string
  String getString(String key, [Map<String, String>? placeholders]) {
    // This will be generated by intl package
    // For now, return a simple lookup
    return _localizedStrings[locale.languageCode]?[key] ?? key;
  }

  // App strings
  String get appTitle => getString('app_title');
  String get welcomeTitle => getString('welcome_title');
  String get selectCharacter => getString('select_character');
  String get boy => getString('boy');
  String get girl => getString('girl');
  String get name => getString('name');
  String get age => getString('age');
  String get email => getString('email');
  String get password => getString('password');
  String get login => getString('login');
  String get register => getString('register');
  String get home => getString('home');
  String get map => getString('map');
  String get rewards => getString('rewards');
  String get settings => getString('settings');
  String get water => getString('water');
  String get sleep => getString('sleep');
  String get walk => getString('walk');
  String get food => getString('food');
  String get play => getString('play');
  String get waterQuestion => getString('water_question');
  String get sleepQuestion => getString('sleep_question');
  String get walkQuestion => getString('walk_question');
  String get foodQuestion => getString('food_question');
  String get cups => getString('cups');
  String get hours => getString('hours');
  String get steps => getString('steps');
  String get points => getString('points');
  String get save => getString('save');
  String get cancel => getString('cancel');
  String get dailyChallenges => getString('daily_challenges');
  String get drinkingWater => getString('drinking_water');
  String get healthyFood => getString('healthy_food');
  String get sleepHours => getString('sleep_hours');
  String get walking => getString('walking');
  String get regionLocked => getString('region_locked');
  String get regionUnlocked => getString('region_unlocked');
  String get regionCompleted => getString('region_completed');
  String get completeGoalsToUnlock => getString('complete_goals_to_unlock');
  String get quiz => getString('quiz');
  String get submit => getString('submit');
  String get score => getString('score');
  String get language => getString('language');
  String get arabic => getString('arabic');
  String get english => getString('english');
  String get logout => getString('logout');
  String get loading => getString('loading');
  String get error => getString('error');
  String get retry => getString('retry');
  String get success => getString('success');
  String get completed => getString('completed');
  String get mapBadgeLabel => getString('map_badge_label');
  String get foodBadgeLabel => getString('food_badge_label');
  String get sleepBadgeLabel => getString('sleep_badge_label');
  String get walkBadgeLabel => getString('walk_badge_label');
  String get gender => getString('gender');
  String get birthDate => getString('birth_date');
  String get pointsLabel => getString('points_label');
  String get edit => getString('edit');
  String get update => getString('update');
  
  String greatCompletedRegion(String region) {
    return getString('great_completed_region').replaceAll('{region}', region);
  }

  static final Map<String, Map<String, String>> _localizedStrings = {
    'ar': {
      'app_title': 'مملكة الأبطال',
      'welcome_title': 'مرحبا بك',
      'select_character': 'اختر شخصيتك',
      'boy': 'ولد',
      'girl': 'بنت',
      'name': 'الاسم',
      'age': 'العمر',
      'email': 'البريد الالكتروني',
      'password': 'كلمة المرور',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'home': 'الرئيسية',
      'map': 'الخريطة',
      'rewards': 'المكافئات',
      'settings': 'الإعدادات',
      'water': 'الماء',
      'sleep': 'النوم',
      'walk': 'المشي',
      'food': 'الطعام الصحي',
      'play': 'لعب',
      'water_question': 'كم كوبا من الماء شربت اليوم؟',
      'sleep_question': 'هل اخذت قسطا كافيا من النوم؟',
      'walk_question': 'هل مشيت مسافه كافيه اليوم؟',
      'food_question': 'هل تناولت طعاما صحيا اليوم؟',
      'cups': 'أكواب',
      'hours': 'ساعات',
      'steps': 'خطوات',
      'points': 'نقاط',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'daily_challenges': 'التحديات اليومية',
      'drinking_water': 'شرب الماء',
      'healthy_food': 'الطعام الصحي',
      'sleep_hours': 'ساعات النوم',
      'walking': 'المشي',
      'region_locked': 'مقفل',
      'region_unlocked': 'مفتوح',
      'region_completed': 'مكتمل',
      'complete_goals_to_unlock': 'أكمل أهداف اليوم لفتح هذه المنطقة',
      'quiz': 'الأسئلة',
      'submit': 'إرسال',
      'score': 'النتيجة',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'logout': 'تسجيل الخروج',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'success': 'نجح',
      'completed': 'مكتمل',
      'great_completed_region': 'رائع لقد اكملت مدينه {region}!!',
      'map_badge_label': 'اكتشف المناطق',
      'food_badge_label': 'طعام صحي',
      'sleep_badge_label': 'نوم كافٍ',
      'walk_badge_label': 'خطوات نشاط',
      'gender': 'الجنس',
      'birth_date': 'تاريخ الميلاد',
      'points_label': 'النقاط المحصلة',
      'edit': 'تعديل',
      'update': 'تحديث',
    },
    'en': {
      'app_title': 'Kingdom of Heroes',
      'welcome_title': 'Welcome',
      'select_character': 'Select your character',
      'boy': 'Boy',
      'girl': 'Girl',
      'name': 'Name',
      'age': 'Age',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'register': 'Register',
      'home': 'Home',
      'map': 'Map',
      'rewards': 'Rewards',
      'settings': 'Settings',
      'water': 'Water',
      'sleep': 'Sleep',
      'walk': 'Walk',
      'food': 'Healthy Food',
      'play': 'Play',
      'water_question': 'How many cups of water did you drink today?',
      'sleep_question': 'Did you get enough sleep?',
      'walk_question': 'Did you walk enough today?',
      'food_question': 'Did you eat healthy food today?',
      'cups': 'cups',
      'hours': 'hours',
      'steps': 'steps',
      'points': 'points',
      'save': 'Save',
      'cancel': 'Cancel',
      'daily_challenges': 'Daily Challenges',
      'drinking_water': 'Drinking Water',
      'healthy_food': 'Healthy Food',
      'sleep_hours': 'Sleep Hours',
      'walking': 'Walking',
      'region_locked': 'Locked',
      'region_unlocked': 'Unlocked',
      'region_completed': 'Completed',
      'complete_goals_to_unlock': 'Complete today\'s goals to unlock this region',
      'quiz': 'Quiz',
      'submit': 'Submit',
      'score': 'Score',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'logout': 'Logout',
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'success': 'Success',
      'completed': 'Completed',
      'great_completed_region': 'Great! You have completed {region} city!!',
      'map_badge_label': 'Discover Regions',
      'food_badge_label': 'Healthy Food',
      'sleep_badge_label': 'Good Sleep',
      'walk_badge_label': 'Active Steps',
      'gender': 'Gender',
      'birth_date': 'Birth Date',
      'points_label': 'Earned Points',
      'edit': 'Edit',
      'update': 'Update',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
